### PR TITLE
Turned this into releasable, working plugin

### PR DESCRIPTION
**Pull request by pookeythekid**
Pretty much the title. Fixed things and stuff to make it a runnable plugin. I also fixed a crapton of bugs, so yeah :D

Actual changes I made:

* Recoded the entire paintball gun so that it uses packets now. This is much better at not destroying the contents of container blocks and signs.
 * Also massively expanded PaintballGunListener's BlockData class (and made it its own separate class), though it turned out to be useless once I went to packets.

* Redesigned the gadget-adding system. Players now own their individual sets of Gadgets; each players' gadgets have their events registered **once**. Re-registering gadgets was a major bug.
 * The MVPGadgets class's _availableGadgets_ contains ownerless gadgets, for the sake of seeing what they are without having redundant listeners registered.

* Added a few settings in messages.yml.

* Made a bunch of OCD edits throughout the code and config files.

* Wrote up an HTML file in the resources folder that covers all commands and permissions. Feel free to add to it if necessary.

* Did I say I fixed a crapton of bugs?

* Added commands /mvpgadgets reload and /gadget
 * /gadget will swap your gadget out for the GUI Gadget and open the GUI display.

* Added config settings guiGadgetWorlds and guiGadgetSlot (I think the latter is correct, too lazy to check right now). Basically self-explanatory.

* Made gadgets functional after a plugin reload with players online, instead of the plugin vomiting NPEs everywhere.

Also, I got very familiar with this plugin's code. I must say, beautiful job @TGRHavoc :)

@JoshMullins if it helps the alert

### CODE REVIEW

**Comment by TGRHavoc** [comment]
Thanks for the compliment :grin:
Just got 'round to reviewing the code. And must say, good job on finding and squashing the bugs.

Totally forgot the debug messages I left in parts :-1: (looking at the committed files, there's still a few Bukkit#broadcastMessage's left). I personally would have put the commands and stuff into a table rather than using lists (again, personal preference. If it works, it works :tongue:)

As for the paintball update, I was originally going to implement this using packets (as you have) however, It would've required some more reflection to NMS code (like in DisguiseListener (I think)) to allow us easily implement it for different versions of Minecraft (so we're not dependent on a particular server version).

Might get back into coding this plugin, still a few gadgets that need implementing (and it may need updating for newer versions of Bukkit).

Note: Haven't tested this but, code looks sound.. If @JoshMullins is OK with it, I'll merge it (if he doesn't respond within a day, I'll merge anyways :wink: )

**Comment by pookeythekid** [comment]
Good to see someone here is still alive c:

This might be a one-and-done for me, idk. Basically the only way I'm
consistently motivated to code anything is if it's to fill an immediate
need for myself or someone else. Otherwise, my discipline level is about
zero. :P

**Comment by TGRHavoc** [comment]
I know what you mean, I find it difficult to find motivation to keep up with projects that don't use myself.

I saw the static version :tongue:, thought it was a temporary thing, I might change the code to allow for different server versions (think I've still got an issue open for that :S), when I've got some spare time. As for testing disguises, I created an offline local server and launched another game using a cracked launcher (pretty useful for testing multiplayer stuff).

**Comment by TGRHavoc** [comment]
@pookeythekid 

I've just started to work on the plugin (need to create a separate release for 1.8.x and newer versions of Bukkit 😞), and I couldn't help but notice something.. I don't think this plugin would work on a large scale (E.g. A Minigame server) because of the way the gadgets are being registered (please, correct me if I'm wrong. I've not done Java in a while). Because you're creating a array (essentially) of  gadgets for each player. So, let's say a server has 100 players, that's 100 UUIDs stored in memory then 600
(Players * Gadgets) Gadgets. I hope that clarifies what I mean by it not being scalable.

So, I thought of a (hopefully better) solution and just wanted to check that I'm not misunderstanding your implementation before I go around deleting everything.

Oh, the solution, if you're wondering is to have a static boolean for each gadget (e.g. in GUIGadget.java) to check if the gadget has already been registered, if it has then just don't do it again.

**Comment by TGRHavoc** [comment]
I've committed to the development branch to better show what I meant. I changed it slightly, instead of each gadget having it's own boolean the main gadget class handles the registration. See 0db3fa44

**Pull request merged**
